// Copyright 2022 SaferPlace

// @generated by protoc-gen-es v0.0.9 with parameter "target=ts"
// @generated from file report/v1/report.proto (package report.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";
import {Incident} from "../../incident/v1/incident_pb.js";

/**
 * @generated from message report.v1.SendReportRequest
 */
export class SendReportRequest extends Message<SendReportRequest> {
  /**
   * @generated from field: incident.v1.Incident incident = 1;
   */
  incident?: Incident;

  constructor(data?: PartialMessage<SendReportRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "report.v1.SendReportRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "incident", kind: "message", T: Incident },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendReportRequest {
    return new SendReportRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendReportRequest {
    return new SendReportRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendReportRequest {
    return new SendReportRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendReportRequest | PlainMessage<SendReportRequest> | undefined, b: SendReportRequest | PlainMessage<SendReportRequest> | undefined): boolean {
    return proto3.util.equals(SendReportRequest, a, b);
  }
}

/**
 * @generated from message report.v1.SendReportResponse
 */
export class SendReportResponse extends Message<SendReportResponse> {
  constructor(data?: PartialMessage<SendReportResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "report.v1.SendReportResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendReportResponse {
    return new SendReportResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendReportResponse {
    return new SendReportResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendReportResponse {
    return new SendReportResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendReportResponse | PlainMessage<SendReportResponse> | undefined, b: SendReportResponse | PlainMessage<SendReportResponse> | undefined): boolean {
    return proto3.util.equals(SendReportResponse, a, b);
  }
}

