// Copyright 2022 SaferPlace

// @generated by protoc-gen-es v0.0.9 with parameter "target=js+dts"
// @generated from file report/v1/report.proto (package report.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";
import {Incident} from "../../incident/v1/incident_pb.js";

/**
 * @generated from message report.v1.SendReportRequest
 */
export const SendReportRequest = proto3.makeMessageType(
  "report.v1.SendReportRequest",
  () => [
    { no: 1, name: "incident", kind: "message", T: Incident },
  ],
);

/**
 * @generated from message report.v1.SendReportResponse
 */
export const SendReportResponse = proto3.makeMessageType(
  "report.v1.SendReportResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

