// Copyright 2022 SaferPlace

// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file report/v1/report.proto (package report.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {SendReportRequest, SendReportResponse} from "./report_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * Report API
 *
 * The Report API allows users to report incidents as they happen.
 *
 * @generated from service report.v1.ReportService
 */
export const ReportService = {
  typeName: "report.v1.ReportService",
  methods: {
    /**
     * SendReport 
     *
     * @generated from rpc report.v1.ReportService.SendReport
     */
    sendReport: {
      name: "SendReport",
      I: SendReportRequest,
      O: SendReportResponse,
      kind: MethodKind.Unary,
    },
  }
};

