// Copyright 2022 SaferPlace

// @generated by protoc-gen-es v1.3.0 with parameter "target=js+dts"
// @generated from file incident/v1/incident.proto (package incident.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * Rough description of the location of incident.
 *
 * @generated from enum incident.v1.Location
 */
export const Location = proto3.makeEnum(
  "incident.v1.Location",
  [
    {no: 0, name: "LOCATION_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "LOCATION_OUTSIDE", localName: "OUTSIDE"},
    {no: 2, name: "LOCATION_INSIDE", localName: "INSIDE"},
    {no: 3, name: "LOCATION_TRANSPORTATION", localName: "TRANSPORTATION"},
  ],
);

/**
 * Transportation defines the method of transportation for the incident.
 *
 * @generated from enum incident.v1.Transportation
 */
export const Transportation = proto3.makeEnum(
  "incident.v1.Transportation",
  [
    {no: 0, name: "TRANSPORTATION_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "TRANSPORTATION_BUS", localName: "BUS"},
    {no: 2, name: "TRANSPORTATION_TRAIN", localName: "TRAIN"},
    {no: 3, name: "TRANSPORTATION_TRAM", localName: "TRAM"},
    {no: 4, name: "TRANSPORTATION_TAXI", localName: "TAXI"},
  ],
);

/**
 * Resolution defines how the incident was resolved, or not yet.
 *
 * @generated from enum incident.v1.Resolution
 */
export const Resolution = proto3.makeEnum(
  "incident.v1.Resolution",
  [
    {no: 0, name: "RESOLUTION_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "RESOLUTION_REJECTED", localName: "REJECTED"},
    {no: 2, name: "RESOLUTION_ACCEPTED", localName: "ACCEPTED"},
    {no: 3, name: "RESOLUTION_ALERTED", localName: "ALERTED"},
  ],
);

/**
 * Incident defines an individual incident as it happened.
 *
 * @generated from message incident.v1.Incident
 */
export const Incident = proto3.makeMessageType(
  "incident.v1.Incident",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "message", T: Timestamp },
    { no: 3, name: "location", kind: "enum", T: proto3.getEnumType(Location) },
    { no: 4, name: "coordinates", kind: "message", T: Coordinates },
    { no: 5, name: "transportation_mode", kind: "enum", T: proto3.getEnumType(Transportation) },
    { no: 6, name: "transportation_identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "resolution", kind: "enum", T: proto3.getEnumType(Resolution) },
    { no: 9, name: "reviewer_comments", kind: "message", T: Comment, repeated: true },
    { no: 10, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message incident.v1.Coordinates
 */
export const Coordinates = proto3.makeMessageType(
  "incident.v1.Coordinates",
  () => [
    { no: 1, name: "lat", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "lon", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * Comment left by the reviewer.
 *
 * @generated from message incident.v1.Comment
 */
export const Comment = proto3.makeMessageType(
  "incident.v1.Comment",
  () => [
    { no: 1, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "author_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "resolution", kind: "enum", T: proto3.getEnumType(Resolution) },
  ],
);

