// Copyright 2023 SaferPlace

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: viewer/v1/viewer.proto

package viewerconnect

import (
	v1 "api.safer.place/viewer/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// ViewerServiceName is the fully-qualified name of the ViewerService service.
	ViewerServiceName = "viewer.v1.ViewerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ViewerServiceViewInRadiusProcedure is the fully-qualified name of the ViewerService's
	// ViewInRadius RPC.
	ViewerServiceViewInRadiusProcedure = "/viewer.v1.ViewerService/ViewInRadius"
	// ViewerServiceViewIncidentProcedure is the fully-qualified name of the ViewerService's
	// ViewIncident RPC.
	ViewerServiceViewIncidentProcedure = "/viewer.v1.ViewerService/ViewIncident"
)

// ViewerServiceClient is a client for the viewer.v1.ViewerService service.
type ViewerServiceClient interface {
	// ViewInRadius provides all incidents within a given radius from a
	// given position.
	ViewInRadius(context.Context, *connect.Request[v1.ViewInRadiusRequest]) (*connect.Response[v1.ViewInRadiusResponse], error)
	// ViewIncident displays the incident information for the specified ID.
	ViewIncident(context.Context, *connect.Request[v1.ViewIncidentRequest]) (*connect.Response[v1.ViewIncidentResponse], error)
}

// NewViewerServiceClient constructs a client for the viewer.v1.ViewerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewViewerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ViewerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &viewerServiceClient{
		viewInRadius: connect.NewClient[v1.ViewInRadiusRequest, v1.ViewInRadiusResponse](
			httpClient,
			baseURL+ViewerServiceViewInRadiusProcedure,
			opts...,
		),
		viewIncident: connect.NewClient[v1.ViewIncidentRequest, v1.ViewIncidentResponse](
			httpClient,
			baseURL+ViewerServiceViewIncidentProcedure,
			opts...,
		),
	}
}

// viewerServiceClient implements ViewerServiceClient.
type viewerServiceClient struct {
	viewInRadius *connect.Client[v1.ViewInRadiusRequest, v1.ViewInRadiusResponse]
	viewIncident *connect.Client[v1.ViewIncidentRequest, v1.ViewIncidentResponse]
}

// ViewInRadius calls viewer.v1.ViewerService.ViewInRadius.
func (c *viewerServiceClient) ViewInRadius(ctx context.Context, req *connect.Request[v1.ViewInRadiusRequest]) (*connect.Response[v1.ViewInRadiusResponse], error) {
	return c.viewInRadius.CallUnary(ctx, req)
}

// ViewIncident calls viewer.v1.ViewerService.ViewIncident.
func (c *viewerServiceClient) ViewIncident(ctx context.Context, req *connect.Request[v1.ViewIncidentRequest]) (*connect.Response[v1.ViewIncidentResponse], error) {
	return c.viewIncident.CallUnary(ctx, req)
}

// ViewerServiceHandler is an implementation of the viewer.v1.ViewerService service.
type ViewerServiceHandler interface {
	// ViewInRadius provides all incidents within a given radius from a
	// given position.
	ViewInRadius(context.Context, *connect.Request[v1.ViewInRadiusRequest]) (*connect.Response[v1.ViewInRadiusResponse], error)
	// ViewIncident displays the incident information for the specified ID.
	ViewIncident(context.Context, *connect.Request[v1.ViewIncidentRequest]) (*connect.Response[v1.ViewIncidentResponse], error)
}

// NewViewerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewViewerServiceHandler(svc ViewerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	viewerServiceViewInRadiusHandler := connect.NewUnaryHandler(
		ViewerServiceViewInRadiusProcedure,
		svc.ViewInRadius,
		opts...,
	)
	viewerServiceViewIncidentHandler := connect.NewUnaryHandler(
		ViewerServiceViewIncidentProcedure,
		svc.ViewIncident,
		opts...,
	)
	return "/viewer.v1.ViewerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ViewerServiceViewInRadiusProcedure:
			viewerServiceViewInRadiusHandler.ServeHTTP(w, r)
		case ViewerServiceViewIncidentProcedure:
			viewerServiceViewIncidentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedViewerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedViewerServiceHandler struct{}

func (UnimplementedViewerServiceHandler) ViewInRadius(context.Context, *connect.Request[v1.ViewInRadiusRequest]) (*connect.Response[v1.ViewInRadiusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("viewer.v1.ViewerService.ViewInRadius is not implemented"))
}

func (UnimplementedViewerServiceHandler) ViewIncident(context.Context, *connect.Request[v1.ViewIncidentRequest]) (*connect.Response[v1.ViewIncidentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("viewer.v1.ViewerService.ViewIncident is not implemented"))
}
