// Copyright 2023 SaferPlace

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: viewer/v1/viewer.proto

package viewer

import (
	v1 "api.safer.place/incident/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ViewInRadiusRequest shows all incidents within specified radius (in meters).
type ViewInRadiusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Center of the search radius
	Center *v1.Coordinates `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	// Radius from the place that the incident happened in, in meters.
	Radius float64 `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *ViewInRadiusRequest) Reset() {
	*x = ViewInRadiusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_viewer_v1_viewer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewInRadiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewInRadiusRequest) ProtoMessage() {}

func (x *ViewInRadiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_viewer_v1_viewer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewInRadiusRequest.ProtoReflect.Descriptor instead.
func (*ViewInRadiusRequest) Descriptor() ([]byte, []int) {
	return file_viewer_v1_viewer_proto_rawDescGZIP(), []int{0}
}

func (x *ViewInRadiusRequest) GetCenter() *v1.Coordinates {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *ViewInRadiusRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type ViewInRadiusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Incidents []*v1.Incident `protobuf:"bytes,1,rep,name=incidents,proto3" json:"incidents,omitempty"`
}

func (x *ViewInRadiusResponse) Reset() {
	*x = ViewInRadiusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_viewer_v1_viewer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewInRadiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewInRadiusResponse) ProtoMessage() {}

func (x *ViewInRadiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_viewer_v1_viewer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewInRadiusResponse.ProtoReflect.Descriptor instead.
func (*ViewInRadiusResponse) Descriptor() ([]byte, []int) {
	return file_viewer_v1_viewer_proto_rawDescGZIP(), []int{1}
}

func (x *ViewInRadiusResponse) GetIncidents() []*v1.Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

// ViewIncidentRequest will show the incident based on the given id.
type ViewIncidentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ViewIncidentRequest) Reset() {
	*x = ViewIncidentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_viewer_v1_viewer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewIncidentRequest) ProtoMessage() {}

func (x *ViewIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_viewer_v1_viewer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewIncidentRequest.ProtoReflect.Descriptor instead.
func (*ViewIncidentRequest) Descriptor() ([]byte, []int) {
	return file_viewer_v1_viewer_proto_rawDescGZIP(), []int{2}
}

func (x *ViewIncidentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ViewIncidentResponse returns the incident for review.
type ViewIncidentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Incident *v1.Incident `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
}

func (x *ViewIncidentResponse) Reset() {
	*x = ViewIncidentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_viewer_v1_viewer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewIncidentResponse) ProtoMessage() {}

func (x *ViewIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_viewer_v1_viewer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewIncidentResponse.ProtoReflect.Descriptor instead.
func (*ViewIncidentResponse) Descriptor() ([]byte, []int) {
	return file_viewer_v1_viewer_proto_rawDescGZIP(), []int{3}
}

func (x *ViewIncidentResponse) GetIncident() *v1.Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

var File_viewer_v1_viewer_proto protoreflect.FileDescriptor

var file_viewer_v1_viewer_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x65, 0x77,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x1a, 0x1a, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5f, 0x0a, 0x13, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x22, 0x4b, 0x0a, 0x14, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x25, 0x0a,
	0x13, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x14, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08,
	0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x32,
	0xb1, 0x01, 0x0a, 0x0d, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x52, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x12, 0x1e, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x49, 0x6e, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x49, 0x6e, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x83, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x69, 0x65, 0x77,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x61, 0x66, 0x65, 0x72, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x56,
	0x69, 0x65, 0x77, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x56, 0x69, 0x65, 0x77, 0x65,
	0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x56,
	0x69, 0x65, 0x77, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_viewer_v1_viewer_proto_rawDescOnce sync.Once
	file_viewer_v1_viewer_proto_rawDescData = file_viewer_v1_viewer_proto_rawDesc
)

func file_viewer_v1_viewer_proto_rawDescGZIP() []byte {
	file_viewer_v1_viewer_proto_rawDescOnce.Do(func() {
		file_viewer_v1_viewer_proto_rawDescData = protoimpl.X.CompressGZIP(file_viewer_v1_viewer_proto_rawDescData)
	})
	return file_viewer_v1_viewer_proto_rawDescData
}

var file_viewer_v1_viewer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_viewer_v1_viewer_proto_goTypes = []interface{}{
	(*ViewInRadiusRequest)(nil),  // 0: viewer.v1.ViewInRadiusRequest
	(*ViewInRadiusResponse)(nil), // 1: viewer.v1.ViewInRadiusResponse
	(*ViewIncidentRequest)(nil),  // 2: viewer.v1.ViewIncidentRequest
	(*ViewIncidentResponse)(nil), // 3: viewer.v1.ViewIncidentResponse
	(*v1.Coordinates)(nil),       // 4: incident.v1.Coordinates
	(*v1.Incident)(nil),          // 5: incident.v1.Incident
}
var file_viewer_v1_viewer_proto_depIdxs = []int32{
	4, // 0: viewer.v1.ViewInRadiusRequest.center:type_name -> incident.v1.Coordinates
	5, // 1: viewer.v1.ViewInRadiusResponse.incidents:type_name -> incident.v1.Incident
	5, // 2: viewer.v1.ViewIncidentResponse.incident:type_name -> incident.v1.Incident
	0, // 3: viewer.v1.ViewerService.ViewInRadius:input_type -> viewer.v1.ViewInRadiusRequest
	2, // 4: viewer.v1.ViewerService.ViewIncident:input_type -> viewer.v1.ViewIncidentRequest
	1, // 5: viewer.v1.ViewerService.ViewInRadius:output_type -> viewer.v1.ViewInRadiusResponse
	3, // 6: viewer.v1.ViewerService.ViewIncident:output_type -> viewer.v1.ViewIncidentResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_viewer_v1_viewer_proto_init() }
func file_viewer_v1_viewer_proto_init() {
	if File_viewer_v1_viewer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_viewer_v1_viewer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewInRadiusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_viewer_v1_viewer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewInRadiusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_viewer_v1_viewer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewIncidentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_viewer_v1_viewer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewIncidentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_viewer_v1_viewer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_viewer_v1_viewer_proto_goTypes,
		DependencyIndexes: file_viewer_v1_viewer_proto_depIdxs,
		MessageInfos:      file_viewer_v1_viewer_proto_msgTypes,
	}.Build()
	File_viewer_v1_viewer_proto = out.File
	file_viewer_v1_viewer_proto_rawDesc = nil
	file_viewer_v1_viewer_proto_goTypes = nil
	file_viewer_v1_viewer_proto_depIdxs = nil
}
