// Copyright 2023 SaferPlace

// @generated by protoc-gen-es v1.3.0 with parameter "target=js+dts"
// @generated from file viewer/v1/viewer.proto (package viewer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Coordinates, Incident } from "../../incident/v1/incident_pb.js";

/**
 * ViewInRadiusRequest shows all incidents within specified radius (in meters).
 *
 * @generated from message viewer.v1.ViewInRadiusRequest
 */
export const ViewInRadiusRequest = proto3.makeMessageType(
  "viewer.v1.ViewInRadiusRequest",
  () => [
    { no: 1, name: "center", kind: "message", T: Coordinates },
    { no: 2, name: "radius", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message viewer.v1.ViewInRadiusResponse
 */
export const ViewInRadiusResponse = proto3.makeMessageType(
  "viewer.v1.ViewInRadiusResponse",
  () => [
    { no: 1, name: "incidents", kind: "message", T: Incident, repeated: true },
  ],
);

/**
 * ViewInRegionRequest shows all incidents in the provided region.
 *
 * @generated from message viewer.v1.ViewInRegionRequest
 */
export const ViewInRegionRequest = proto3.makeMessageType(
  "viewer.v1.ViewInRegionRequest",
  () => [
    { no: 1, name: "region", kind: "message", T: Region },
    { no: 2, name: "since", kind: "message", T: Timestamp },
  ],
);

/**
 * ViewInRegionResponse returns the list of incidents.
 *
 * @generated from message viewer.v1.ViewInRegionResponse
 */
export const ViewInRegionResponse = proto3.makeMessageType(
  "viewer.v1.ViewInRegionResponse",
  () => [
    { no: 1, name: "incidents", kind: "message", T: Incident, repeated: true },
  ],
);

/**
 * ViewIncidentRequest will show the incident based on the given id.
 *
 * @generated from message viewer.v1.ViewIncidentRequest
 */
export const ViewIncidentRequest = proto3.makeMessageType(
  "viewer.v1.ViewIncidentRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ViewIncidentResponse returns the incident for review.
 *
 * @generated from message viewer.v1.ViewIncidentResponse
 */
export const ViewIncidentResponse = proto3.makeMessageType(
  "viewer.v1.ViewIncidentResponse",
  () => [
    { no: 1, name: "incident", kind: "message", T: Incident },
  ],
);

/**
 * ViewAlertingRequest allows to specify which alerts to view which are alerting.
 *
 * @generated from message viewer.v1.ViewAlertingRequest
 */
export const ViewAlertingRequest = proto3.makeMessageType(
  "viewer.v1.ViewAlertingRequest",
  () => [
    { no: 1, name: "region", kind: "message", T: Region },
    { no: 2, name: "since", kind: "message", T: Timestamp },
  ],
);

/**
 * ViewAlertingResponse returns the list of incidents.
 *
 * @generated from message viewer.v1.ViewAlertingResponse
 */
export const ViewAlertingResponse = proto3.makeMessageType(
  "viewer.v1.ViewAlertingResponse",
  () => [
    { no: 1, name: "incidents", kind: "message", T: Incident, repeated: true },
  ],
);

/**
 * Region defines a block of coordinates which can be used for getting incidents without revealing
 * the precise location of the user, but rather multiple small requests can be made around the user.
 * This is formed by creating a box where the area of interest lies between north and south, and
 * east and west.
 *   (north <= $lattitude <= south) && (east <= $longitude <= west)
 *
 * @generated from message viewer.v1.Region
 */
export const Region = proto3.makeMessageType(
  "viewer.v1.Region",
  () => [
    { no: 1, name: "north", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "south", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "east", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "west", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

