// Copyright 2023 SaferPlace

// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+dts"
// @generated from file viewer/v1/viewer.proto (package viewer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ViewInRadiusRequest, ViewInRadiusResponse } from "./viewer_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ViewerService provices the ability to view incidents.
 *
 * @generated from service viewer.v1.ViewerService
 */
export const ViewerService = {
  typeName: "viewer.v1.ViewerService",
  methods: {
    /**
     * ViewInRadius provides all incidents within a given radius from a
     * given position.
     *
     * @generated from rpc viewer.v1.ViewerService.ViewInRadius
     */
    viewInRadius: {
      name: "ViewInRadius",
      I: ViewInRadiusRequest,
      O: ViewInRadiusResponse,
      kind: MethodKind.Unary,
    },
  }
};

