// Copyright 2023 SaferPlace

// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+dts"
// @generated from file viewer/v1/viewer.proto (package viewer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ViewAlertingRequest, ViewAlertingResponse, ViewIncidentRequest, ViewIncidentResponse, ViewInRadiusRequest, ViewInRadiusResponse } from "./viewer_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ViewerService provices the ability to view incidents.
 *
 * @generated from service viewer.v1.ViewerService
 */
export const ViewerService = {
  typeName: "viewer.v1.ViewerService",
  methods: {
    /**
     * ViewInRadius provides all incidents within a given radius from a
     * given position.
     *
     * @generated from rpc viewer.v1.ViewerService.ViewInRadius
     */
    viewInRadius: {
      name: "ViewInRadius",
      I: ViewInRadiusRequest,
      O: ViewInRadiusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ViewIncident displays the incident information for the specified ID.
     *
     * @generated from rpc viewer.v1.ViewerService.ViewIncident
     */
    viewIncident: {
      name: "ViewIncident",
      I: ViewIncidentRequest,
      O: ViewIncidentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ViewAlertingIncidents shows the incidents in the specified area of interest
     *
     * @generated from rpc viewer.v1.ViewerService.ViewAlerting
     */
    viewAlerting: {
      name: "ViewAlerting",
      I: ViewAlertingRequest,
      O: ViewAlertingResponse,
      kind: MethodKind.Unary,
    },
  }
};

