// Copyright 2023 SaferPlace

// @generated by protoc-gen-es v1.3.0 with parameter "target=js+dts"
// @generated from file viewer/v1/viewer.proto (package viewer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Coordinates, Incident } from "../../incident/v1/incident_pb.js";

/**
 * ViewInRadiusRequest shows all incidents within specified radius (in meters).
 *
 * @generated from message viewer.v1.ViewInRadiusRequest
 */
export declare class ViewInRadiusRequest extends Message<ViewInRadiusRequest> {
  /**
   * Center of the search radius
   *
   * @generated from field: incident.v1.Coordinates center = 1;
   */
  center?: Coordinates;

  /**
   * Radius from the place that the incident happened in, in meters.
   *
   * @generated from field: double radius = 2;
   */
  radius: number;

  constructor(data?: PartialMessage<ViewInRadiusRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viewer.v1.ViewInRadiusRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewInRadiusRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewInRadiusRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewInRadiusRequest;

  static equals(a: ViewInRadiusRequest | PlainMessage<ViewInRadiusRequest> | undefined, b: ViewInRadiusRequest | PlainMessage<ViewInRadiusRequest> | undefined): boolean;
}

/**
 * @generated from message viewer.v1.ViewInRadiusResponse
 */
export declare class ViewInRadiusResponse extends Message<ViewInRadiusResponse> {
  /**
   * @generated from field: repeated incident.v1.Incident incidents = 1;
   */
  incidents: Incident[];

  constructor(data?: PartialMessage<ViewInRadiusResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viewer.v1.ViewInRadiusResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewInRadiusResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewInRadiusResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewInRadiusResponse;

  static equals(a: ViewInRadiusResponse | PlainMessage<ViewInRadiusResponse> | undefined, b: ViewInRadiusResponse | PlainMessage<ViewInRadiusResponse> | undefined): boolean;
}

/**
 * ViewIncidentRequest will show the incident based on the given id.
 *
 * @generated from message viewer.v1.ViewIncidentRequest
 */
export declare class ViewIncidentRequest extends Message<ViewIncidentRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<ViewIncidentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viewer.v1.ViewIncidentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewIncidentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewIncidentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewIncidentRequest;

  static equals(a: ViewIncidentRequest | PlainMessage<ViewIncidentRequest> | undefined, b: ViewIncidentRequest | PlainMessage<ViewIncidentRequest> | undefined): boolean;
}

/**
 * ViewIncidentResponse returns the incident for review.
 *
 * @generated from message viewer.v1.ViewIncidentResponse
 */
export declare class ViewIncidentResponse extends Message<ViewIncidentResponse> {
  /**
   * @generated from field: incident.v1.Incident incident = 1;
   */
  incident?: Incident;

  constructor(data?: PartialMessage<ViewIncidentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viewer.v1.ViewIncidentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewIncidentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewIncidentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewIncidentResponse;

  static equals(a: ViewIncidentResponse | PlainMessage<ViewIncidentResponse> | undefined, b: ViewIncidentResponse | PlainMessage<ViewIncidentResponse> | undefined): boolean;
}

