// Copyright 2023 SaferPlace

// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+dts"
// @generated from file viewer/v1/viewer.proto (package viewer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ViewAlertingRequest, ViewAlertingResponse, ViewIncidentRequest, ViewIncidentResponse, ViewInRadiusRequest, ViewInRadiusResponse } from "./viewer_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ViewerService provices the ability to view incidents.
 *
 * @generated from service viewer.v1.ViewerService
 */
export declare const ViewerService: {
  readonly typeName: "viewer.v1.ViewerService",
  readonly methods: {
    /**
     * ViewInRadius provides all incidents within a given radius from a
     * given position.
     *
     * @generated from rpc viewer.v1.ViewerService.ViewInRadius
     */
    readonly viewInRadius: {
      readonly name: "ViewInRadius",
      readonly I: typeof ViewInRadiusRequest,
      readonly O: typeof ViewInRadiusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ViewIncident displays the incident information for the specified ID.
     *
     * @generated from rpc viewer.v1.ViewerService.ViewIncident
     */
    readonly viewIncident: {
      readonly name: "ViewIncident",
      readonly I: typeof ViewIncidentRequest,
      readonly O: typeof ViewIncidentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ViewAlertingIncidents shows the incidents in the specified area of interest
     *
     * @generated from rpc viewer.v1.ViewerService.ViewAlerting
     */
    readonly viewAlerting: {
      readonly name: "ViewAlerting",
      readonly I: typeof ViewAlertingRequest,
      readonly O: typeof ViewAlertingResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

