// Copyright 2022 SaferPlace

// @generated by protoc-gen-es v0.0.9 with parameter "target=js+dts"
// @generated from file review/v1/review.proto (package review.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";
import {Incident, Resolution} from "../../incident/v1/incident_pb.js";

/**
 * StreamIncidentsRequest is empty
 *
 * @generated from message review.v1.StreamIncidentsRequest
 */
export const StreamIncidentsRequest = proto3.makeMessageType(
  "review.v1.StreamIncidentsRequest",
  [],
);

/**
 * StreamIncidentsResponse is a stream of incidents.
 *
 * @generated from message review.v1.StreamIncidentsResponse
 */
export const StreamIncidentsResponse = proto3.makeMessageType(
  "review.v1.StreamIncidentsResponse",
  () => [
    { no: 1, name: "incident", kind: "message", T: Incident },
  ],
);

/**
 * IncomingIncidentRequest has the incident on which the reviewer should respond.
 *
 * @generated from message review.v1.ReviewIncidentRequest
 */
export const ReviewIncidentRequest = proto3.makeMessageType(
  "review.v1.ReviewIncidentRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "resolution", kind: "enum", T: proto3.getEnumType(Resolution) },
  ],
);

/**
 * ReviewIncidentResponse is empty
 *
 * @generated from message review.v1.ReviewIncidentResponse
 */
export const ReviewIncidentResponse = proto3.makeMessageType(
  "review.v1.ReviewIncidentResponse",
  [],
);

/**
 * @generated from message review.v1.WaitForIncidentRequest
 */
export const WaitForIncidentRequest = proto3.makeMessageType(
  "review.v1.WaitForIncidentRequest",
  [],
);

/**
 * @generated from message review.v1.WaitForIncidentResponse
 */
export const WaitForIncidentResponse = proto3.makeMessageType(
  "review.v1.WaitForIncidentResponse",
  () => [
    { no: 1, name: "incident", kind: "message", T: Incident },
  ],
);

