// Copyright 2022 SaferPlace

// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file review/v1/review.proto (package review.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ReviewIncidentRequest, ReviewIncidentResponse, StreamIncidentsRequest, StreamIncidentsResponse} from "./review_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * Review API
 *
 * The review API is used by the reviewers to decide the faith of a given report
 *
 * @generated from service review.v1.ReviewService
 */
export declare const ReviewService: {
  readonly typeName: "review.v1.ReviewService",
  readonly methods: {
    /**
     * @generated from rpc review.v1.ReviewService.StreamIncidents
     */
    readonly streamIncidents: {
      readonly name: "StreamIncidents",
      readonly I: typeof StreamIncidentsRequest,
      readonly O: typeof StreamIncidentsResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * ReviewIncident contains a stream of incoming incidents.
     *
     * @generated from rpc review.v1.ReviewService.ReviewIncident
     */
    readonly reviewIncident: {
      readonly name: "ReviewIncident",
      readonly I: typeof ReviewIncidentRequest,
      readonly O: typeof ReviewIncidentResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

