name: Pull Request
on: pull_request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      # Disabled the breaking changes check before we have a stable v1 API.
      # - uses: bufbuild/buf-breaking-action@v1
      #  with:
      #    against: 'https://github.com/saferplace/api.git#branch=main'
