name: Push
on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the generated branch so we have it ready
      - uses: actions/checkout@v3
        with:
          ref: 'generated'
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.9.0
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/saferplace/api.git#branch=main'
      - name: Generate and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch generated
          git reset --hard main
          buf generate
          git add -A
          git commit -m "Generate Protobufs"
          git push origin generated --force
          
