name: Tag
on:
  push:
    tags: [ v* ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the generated branch so we have it ready
      - uses: actions/checkout@v3
        with:
          ref: 'generated'
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saferplace'
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - run: pnpm version ${{ github.ref_name }} --git-tag-version=false
      - run: pnpm publish --no-git-checks --publish-branch=generated
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
